### ISSUE TITLE
Xcode 8.2.1 运行报错

### ISSUE THREAD

**Issue by jianjianhao** [tingxins/SakuraKit#1]
<img width="389" alt="9b367d54-917b-4902-ba0d-2fb0a4c724e0" src="https://user-images.githubusercontent.com/12797357/29808101-47281fa0-8cc9-11e7-82cc-b5467b068a74.png">

**Comment by tingxins** [comment]
这个是因为 Xcode 8.xx 版本无法识别的原因。Xcode 9 是可以的。

Xcode 8 可选替代方案：

```

if ([[UIDevice currentDevice].systemVersion doubleValue] >= 10.0) {
        tabBarController.tabBar.sakura
        .unselectedItemTintColor(@"Global.tabTitleColor");
} else {
        
}

```
