### ISSUE TITLE
远程资源包下载链接无法使用，可否将远程资源包放在github上，我们可以看下远程资源包是什么样子

### ISSUE THREAD

**Issue by Zss1990** [tingxins/SakuraKit#13]
跑demo时候，发现SakuraKit离线下载那个接口链接“http://rapapi.org/mockjsdata/21815/theme/list”，下载不了，能麻烦看下下载的资源包是什么样子的吗？

**Comment by tingxins** [comment]
rap 服务跪了，一直没人维护。
相关资源可到 [此处下载](https://github.com/tingxins/Resource)
详情可以看看 [这篇文章](http://tingxins.cn/2017/08/27/ios-theme-skin-resolution/)
