### ISSUE TITLE
pod 文件出错

### ISSUE THREAD

**Issue by 907064772** [tingxins/SakuraKit#3]
pod 'SakuraKit'
提示找不到这个框架

**Comment by tingxins** [comment]
尝试更新本地 pod 索引.

**Comment by 907064772** [comment]
emmmm，确实搜不到你的库，我更新到最新了

**Comment by tingxins** [comment]
版本是有的呀。

![](http://image.tingxins.cn/github/issues/Snip20170905_2.png)

把本地 search index 删了，再运行 pod search  SakuraKit
